import Main_Header from "@/components/header/main-header";
import "./globals.css";
import Main_Footer from "@/components/footer/main-footer";

export const metadata = {
  title: "Juan Carlos Rivera",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-white" lang="en">
      <body className="bg-[#96c5f7]">
      <Main_Header />
      {children}
      </body>
      <Main_Footer />
    </html>
  );
}
